spring.application.name=bolao-copa

# Replace 'localhost:3306' with your host and 'your_database_name' with your schema name
spring.datasource.url=jdbc:mysql://localhost:3306/copadomundo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Standard modern MySQL driver (automatically inferred by Spring Boot, but good practice to explicitly state)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver